### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by henrriusdev** [henrriusdev/neploy#6]
I need to implement for the onboarding creation the:

- [ ] Creation of the admin user (we will call it as Super Dev account) (#7)
- [x] Creation of the roles. (#13)
- [x] Web metadata (colors, name, and more) (#14)
![image](https://github.com/user-attachments/assets/172a5769-0d0e-448a-ac9e-59ef421d5c6a)
